version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bizsearch24-web
    restart: always
    ports:
      - "3005:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
