export const CATEGORIES = [
  "Accountants & Auditors",
  "Accounting",
  "Advertising & Marketing",
  "Agricultural Services",
  "Agriculture",
  "Air Conditioning & Refrigeration",
  "Appliance Repairs",
  "Architects",
  "Architectural",
  "Attorneys & Lawyers",
  "Auto Repairs & Mechanics",
  "Automotive",
  "Bakeries",
  "Banks",
  "Beauty Salons",
  "Bed & Breakfast",
  "Builders & Contractors",
  "Business Consultants",
  "Car Dealerships",
  "Car Hire",
  "Catering Services",
  "Child Care",
  "Civil Engineering",
  "Cleaning Services",
  "Clothing Boutiques",
  "Computer Repairs & IT",
  "Construction",
  "Consulting",
  "Courier Services",
  "Creative Design",
  "Dentistry",
  "Dentists",
  "Digital Marketing",
  "Doctors & Medical",
  "Driving Schools",
  "Dry Cleaners",
  "Education",
  "Electrical",
  "Electricians",
  "Engineering Services",
  "Entertainment",
  "Estate Agents",
  "Event Planners",
  "Farming Equipment",
  "Financial",
  "Financial Advisors",
  "Florists",
  "Food & Beverage",
  "Funeral Services",
  "Furniture Stores",
  "Garages & Service Stations",
  "Garden Services",
  "Graphic Designers",
  "Guest Houses",
  "Hairdressers",
  "Hardware Stores",
  "Health & Wellness",
  "Healthcare",
  "Hospitality",
  "Hotels",
  "Human Resources",
  "IT Support",
  "Information Technology",
  "Insurance",
  "Insurance Brokers",
  "Interior Designers",
  "Jewellers",
  "Landscaping",
  "Legal",
  "Locksmiths",
  "Logistics",
  "Logistics & Transport",
  "Manufacturing",
  "Marketing",
  "Massage Therapists",
  "Mechanical",
  "Mechanics",
  "Media",
  "Mining",
  "Moving Companies",
  "Optometrists",
  "Painters",
  "Pest Control",
  "Pet Services & Vets",
  "Pharmaceuticals",
  "Pharmacies",
  "Photographers",
  "Plumbers",
  "Printing Services",
  "Property",
  "Property Management",
  "Real Estate",
  "Restaurants",
  "Retail",
  "Roofing Contractors",
  "Schools & Education",
  "Security",
  "Security Companies",
  "Solar Power Installers",
  "Spas",
  "Supermarkets",
  "Taking & Delivery",
  "Taxis & Shuttles",
  "Telecommunications",
  "Tourism",
  "Towing Services",
  "Training Providers",
  "Transport",
  "Travel Agents",
  "Upholsterers",
  "Veterinarian",
  "Waste Management",
  "Web Designers",
  "Wedding Planners",
  "Welding",
  "Wholesale",
  "Wineries",
  "Yoga Studios"
];
